"""Desktop pet event names shared by demos and future agent wiring."""

from __future__ import annotations

PET_EVENT_IDLE = "idle"
PET_EVENT_LONG_IDLE = "long_idle"
PET_EVENT_WAKE = "wake"
PET_EVENT_USER_TOUCH = "user_touch"
PET_EVENT_CHAT_NORMAL = "chat_normal"
PET_EVENT_CHAT_EXPLAIN = "chat_explain"
PET_EVENT_CHAT_HARD = "chat_hard"
PET_EVENT_REPEAT_QUESTION = "repeat_question"
PET_EVENT_SHOCK = "shock"
PET_EVENT_SAD = "sad"
PET_EVENT_USER_SCOLD = "user_scold"
PET_EVENT_USER_PRAISE = "user_praise"
PET_EVENT_STRONG_PRAISE = "strong_praise"
PET_EVENT_SHY = "shy"

PET_EVENT_TASK_START = "task_start"
PET_EVENT_AUTO_SIT_IDLE = "auto_sit_idle"
PET_EVENT_SIT_IDLE = "sit_idle"
PET_EVENT_IDLE_SITTING = "idle_sitting"
PET_EVENT_SIT_DOWN = "sit_down"
PET_EVENT_SITTING_IDLE = "sitting_idle"
PET_EVENT_SITTING_WORKING = "sitting_working"
PET_EVENT_BUSY = "busy"
PET_EVENT_THINKING = "thinking"
PET_EVENT_PROCESSING = "processing"
PET_EVENT_OUTPUTTING = "outputting"
PET_EVENT_COMPLETE = "complete"
PET_EVENT_WORK_COMPLETE = "work_complete"
PET_EVENT_BACK_TO_IDLE = "back_to_idle"
PET_EVENT_STAND_UP = "stand_up"
PET_EVENT_FULL_LOOP = "full_loop"
PET_EVENT_SLEEP = "sleep"
PET_EVENT_SLEEPING_IDLE = "sleeping_idle"
PET_EVENT_WAKE_UP = "wake_up"
